version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - yarn install
      - yarn build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://cedricholz-portfolio-website --delete
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
